package weissmoon.core;

import com.google.common.collect.Lists;
import org.apache.logging.log4j.*;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.*;
import net.minecraftforge.fml.common.Mod.*;
import net.minecraftforge.fml.common.event.*;
import net.minecraftforge.fml.common.registry.GameRegistry;
import weissmoon.core.command.TogglePVP;
import weissmoon.core.event.EntityDrop;
import weissmoon.core.handler.ConfigurationHandler;
import weissmoon.core.item.*;
import weissmoon.core.lib.*;
import weissmoon.core.network.PacketHandler;
import weissmoon.core.proxy.CommonProxy;

import java.io.File;


@Mod(modid = ReferenceCore.MOD_ID, name = ReferenceCore.MOD_NAME, version = ReferenceCore.VERSION, dependencies = "required-after:Forge@[12.16.1.1887,)", guiFactory = ReferenceCore.GUI_FACTORY_CLASS)
public class WeissCore{
    @Instance(ReferenceCore.MOD_ID)
    public static WeissCore instance;
    public Logger logger = LogManager.getLogger("WeissCore");

    @SidedProxy(clientSide = "weissmoon.core.proxy.ClientProxy", serverSide = "weissmoon.core.proxy.ServerProxy")
    public static CommonProxy proxy;

    /**Modules*/
    //Weisscore Dummy item
    private boolean dummyInitialized;
    public void setDummyItem (){
        instance.dummyInitialized = true;
    }
    //Keyhandler and network
    private boolean keyHandler = false;
    public void initKeyHandler (){
        instance.keyHandler = true;
    }

    //private boolean dummyCoreInitialized = false;


    @EventHandler
    public void preInit (FMLPreInitializationEvent event){
        ModMetadata md = event.getModMetadata();
        md.autogenerated = false;
        md.description = ReferenceCore.DESCRIPTION;
        md.authorList = Lists.newArrayList(ReferenceCore.AUTHOR);
        ConfigurationHandler.init(new File(event.getModConfigurationDirectory().getAbsolutePath() + File.separator + ReferenceCore.AUTHOR + File.separator + ReferenceCore.MOD_ID + ".cfg"));
        if (instance.dummyInitialized){
            GameRegistry.register(CoreDummyItems.dummyItem);
            CoreDummyItems.initDummyItems();
            CoreDummyItems.initRecipes();
        }
        if (keyHandler)
        PacketHandler.init();
    }

    @EventHandler
    public void init (FMLInitializationEvent event){
        MinecraftForge.EVENT_BUS.register(new EntityDrop());
        proxy.registerEventHandler();
        if (keyHandler)
        proxy.registerKeyHandler();
        //proxy.initRenderer();
    }

    @EventHandler
    public void postInit (FMLPostInitializationEvent event){
        proxy.initRenderer();
    }

    @EventHandler
    public void serverStarting (FMLServerStartingEvent evt){
        evt.registerServerCommand(new TogglePVP(evt.getServer()));
    }

    public static ItemStack newDummyItemStack (String name){
        return CoreDummyItems.dummyItem.newDummyItemStack(name, 1);
    }

    public static ItemStack newDummyItemStack (String name, int size){
        return CoreDummyItems.dummyItem.newDummyItemStack(name, size);
    }

}