package weissmoon.core;

//import weissmoon.core.handler.OreDictinaryCondense;
import net.minecraftforge.fml.common.*;
import net.minecraftforge.fml.common.event.*;
import net.minecraftforge.fml.common.registry.GameRegistry;
import weissmoon.core.item.CoreDummyItems;
import weissmoon.core.lib.ReferenceCore;

import java.io.File;

@Mod(modid = ReferenceCore.MOD_ID+"terminal", name = ReferenceCore.MOD_NAME+"terminal", version = ReferenceCore.VERSION, dependencies = "required-after:Forge@[10.12.2.1121,);after:*")
public class WeissCoreTerminal{

    @Mod.EventHandler
    public void preInit (FMLPreInitializationEvent event){
        ModMetadata md = event.getModMetadata();
        md.autogenerated = false;
        md.parent = ReferenceCore.MOD_ID;
        //OreDictinaryCondense.init(new File(event.getModConfigurationDirectory().getAbsolutePath() + File.separator + ReferenceCore.AUTHOR + File.separator + "OreCondense.cfg"),
                                           //event.getModConfigurationDirectory().getAbsoluteFile() + File.separator + ReferenceCore.AUTHOR + File.separator + "OreCondense" + File.separator);

        //GameRegistry.register(new TestItem());
    }

    @Mod.EventHandler
    public void postInit (FMLPostInitializationEvent event){
        WeissCore.proxy.registerRenderOverride();
        //OreDictinaryCondense.loadCofiguration();
    }
}
